### ISSUE TITLE
Empty component types should not require allocation

### ISSUE THREAD

**Issue by dbralir** [dbralir/ginseng#1]
Empty component types are often used as tags, such as `struct is_alive {};`. Since there is no data to access within these types, and since the user does not care about the identity of a tag type, these types should require no allocation.

Possible solutions:

- Store `nullptr` for these components.
  - Creating a reference to `nullptr` is illegal, but "usually works".
- Store a pointer to the same static object for all components.
  - Must be careful to avoid ODR violations.
  - Have to figure out some way to avoid accidentally calling `delete`.
- Provide a `tag<T>` template to specifically mark a component as a tag.
  - May cause confusion between `tag<T>` and `T` components.
  - Probably the safest solution.
  - Must allow storing both `tag<T>` and `T` components in the same entity.

**Comment by benbenolson** [comment]
It appears as if you've got a conundrum: implementing a possibly messy solution to your issue, or just throwing a `nullptr` in there and be done with it.  In order to future-proof this library, I think that you should definitely choose either the second or third option.  Since the second option seems extremely risky and likely to result in lots of issues down the road, I would opt for the third option.
